### ISSUE TITLE
Pointer offset on screen

### ISSUE THREAD

**Issue by ThePreviousOne** [quen/kanjirecog#1]
Version 1.0 F-droid build

See video
[recording_20161225_071204.mp4.zip](https://github.com/quen/kanjirecog/files/672814/recording_20161225_071204.mp4.zip)

**Comment by SebiderSushi** [comment]
A bit late but: This looks familiar. I always encountered the same effect when changing screen density using `wm density` on command line.
 On Android 7.0 or later this is somehow fixed in the framework.
